# Georgios Gerasimos Leventopoulos csd4152  
# Assignment 1   hy457  Intro to Security Systems

all:
	gcc -o a.out cs457_crypto.c
	./a.out

otp:
	gcc -o a.out cs457_crypto.c
	./a.out

caesars:
	gcc -o a.out cs457_crypto.c
	./a.out

#playfair:

#affine:

#feistel:

clean:
	rm -rf *.o
	rm -rf a.out