# Georgios Gerasimos Leventopoulos csd4152  
# Assignment 1   hy457  Intro to Security Systems

all:
	gcc test1.c

clean:
	rm -rf *.o
	rm -rf a.out

#otp:

#caesars:

#playfair:

#affine: