# Georgios Gerasimos Leventopoulos csd4152  
# Assignment 1   hy457  Intro to Security Systems

otp:
	gcc -o a.out otp.c
	./a.out

caesars:
	gcc -o a.out caesars.c
	./a.out

playfair:
	gcc -o a.out playfair.c
	./a.out

affine:
	gcc -o a.out affine.c
	./a.out

feistel:
	gcc -o a.out feistel.c
	./a.out

clean:
	rm -rf *.o
	rm -rf a.out